Miscellaneous Cleanups
Unidata/siphon pull request #830
Opened 2024-11-08 18:19 UTC by dopplershift

#### Description Of Changes
* Remove outdated Travis (and AppVeyor) info
* Remove outdated `TODO.md`
* Make linkchecker pass (Fixes #828)
* Clean up deprecation warnings from `utcnow()`
* Clean up suppression of warnings related to setting `.units` on `DataFrame`s
* Make test suite run with warnings as errors

#### Checklist

- [x] Closes #828
- [x] Fully documented

2024-11-12 01:10 UTC, dcamron requested changes
I guess they don't call it codegrammar

2024-11-12 17:06 UTC, dopplershift commented on docs/developerguide.rst
> +are also checked using the ``doc8`` tool, and spelling is checked using the ``codespell``.
Copy/pasted from MetPy 😆

2024-11-12 20:13 UTC, dopplershift commented
In addition to addressing the review comments, I went ahead and pushed a commit that enables Sphinx nitpicky mode and cleans up all of the issues that identified.

2024-11-15 21:30 UTC, dcamron approved these changes

2024-11-15 21:30 UTC, merged